[package]
name = "autoperm"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"], optional = true }
itertools = "0.10.3"
petgraph = "0.6"

[dev-dependencies]
bfi = { git = "https://github.com/Alextopher/bfi.git", branch = "main" }
rand = "0.8.5"
quickcheck = "1"
quickcheck_macros = "1"
rayon = "1.5.3"

[[bin]]
name = "autoperm"
required_features = ["dep:clap"]
